name: Welcome to the A.Golz page
description: Bookmark this to keep an eye on updates! (:
avatar: https://raw.githubusercontent.com/AGolz/by_me/main/avatar.png
url: https://agolz.github.io/by_me
baseurl: "/by_me"

footer-links:
  github: AGolz
